### ISSUE TITLE
Add minimum pyproject.toml so project repo can be installed in learner environments

### ISSUE THREAD

**Issue by bielsnohr** [carpentries-incubator/python-intermediate-development#278]
As mentioned in #268, the lack of a way to easily install the project repo in a virtual environment makes it quite difficult to navigate some aspects of the course, particularly exercising parts of the IDE and testing. It is worth noting, that almost any Python project I have ever worked on requires an editable install of the package. I recommend we return to doing the same at the beginning of the lesson.

On the practical side, this requires a fairly rudimentary `pyproject.toml` to get running:

```toml
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "python-intermediate-inflammation"
version = "0.0.0"
requires-python = ">=3.8"

[tool.setuptools]
packages = ["inflammation"]
```

This would be bundled into the initial learner project. Only thing that would need to be added is an install command put somewhere in the course (probably before the testing lesson):

```bash
pip install -e .
```
