### ISSUE TITLE
Use quotes for entries with spaces in yml config in episode 15 on continuous integration 

### ISSUE THREAD

**Issue by anenadic** [carpentries-incubator/python-intermediate-development#68]
Some examples are using quotes for multi word parameter values but others are not. E.g. in example:

```
first_scaled_by:
  - Hans Meyer
  - Ludwig Purtscheller
```

and example: 
```
...
height:
  value: 5892
  unit: metres
  measured:
    year: 2008
    by: Kilimanjaro 2008 Precise Height Measurement Expedition
```
